name: K6 Performance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the project with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start services with Docker Compose
        run: docker-compose up db app prometheus grafana agent influxdb --detach

      - name: Wait for services to start
        run: sleep 30

      - name: Set permissions
        run: chmod -R 777 ./k6-scripts


      - name: Run k6 performance tests
        run: |
          docker run --rm -v ${{ github.workspace }}/k6-scripts:/k6-scripts grafana/k6:latest run /k6-scripts/test.js \
            --out influxdb=http://k6:k6password@localhost:8086/k6 \
            --out json=/k6-scripts/results.json

      - name: Upload k6 results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: ./k6-scripts/results.json
