name: Performance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    services:
      influxdb:
        image: influxdb:1.8
        ports:
          - 8086:8086
        env:
          INFLUXDB_DB: k6
          INFLUXDB_ADMIN_USER: admin
          INFLUXDB_ADMIN_PASSWORD: admin
          INFLUXDB_USER: k6
          INFLUXDB_USER_PASSWORD: k6password

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start services with Docker Compose
        run: docker-compose up db app prometheus grafana influxdb

      - name: Wait for services to start
        run: sleep 20

      - name: Run k6 performance tests
        run: |
          docker run --rm -v ${{ github.workspace }}/k6-scripts:/k6-scripts grafana/k6:latest run /k6-scripts/test.js \
            --out influxdb=http://k6:k6password@localhost:8086/k6 \
            --out json=/k6-scripts/results.json

      - name: Upload k6 results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: ./k6-scripts/results.json
